{"Launchpad":"https://bugs.launchpad.net/bugs/1308918","Id":"1308918","Gerrit":"https://review.openstack.org/101556","IdGerrit":"101556","IdCommit":"4824239730cf628df20d28d0e72ec02c4f7139a8","Files":["openstack_auth/backend.py","openstack_auth/user.py","openstack_auth/utils.py","openstack_auth/views.py"],"Lines_Inseted":86,"Lines_Deleted":26,"CommitParent":"5c8b0c78f28a9fdc8eea91bc0d89879523dd1959","Classification":"Bug","KeywordsTitle":"session, timed out","Description":"expired, timed out, reproduce","KeywordsCommit":"Adding, allows, check,  patch is requiered","Comments":"It's a bug report, in the description they show you how you can reproduce the bug."}